# Generated by Django 4.2.28 on 2026-03-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0120_issueview_archived_at"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE IF EXISTS public.projects DROP COLUMN IF EXISTS automation_metadata;
            ALTER TABLE IF EXISTS public.projects DROP COLUMN IF EXISTS automation_sector_id;
            ALTER TABLE IF EXISTS public.projects DROP COLUMN IF EXISTS automation_area_id;
            ALTER TABLE IF EXISTS public.issues DROP COLUMN IF EXISTS automatable;
            ALTER TABLE IF EXISTS public.issues DROP COLUMN IF EXISTS automation_metadata;
            ALTER TABLE IF EXISTS public.issues DROP COLUMN IF EXISTS automation_structure_override;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
